### ISSUE TITLE
Upgrade to Guzzle 7

### ISSUE THREAD

**Issue by Kaishiyoku** [Jeroen-G/Flickr#10]
Hello, I'm using your package for a Laravel-based project and recently a new major version of Laravel has been released which uses Guzzle 7. Would it be possible to upgrade your package to use Guzzle 7? I will take a look if I can make a pull request for you.

Update: Pull request: https://github.com/Jeroen-G/Flickr/pull/11

**Comment by Kaishiyoku** [comment]
Pull request is merged. Thank you for the fast response; have a great day.

**Comment by Jeroen-G** [comment]
Have fun using the package!
