### ISSUE TITLE
can not make it to work.

### ISSUE THREAD

**Issue by mpixelz** [Jeroen-G/Flickr#2]
Hi,
i was following an article regarding flickr recent pictures for laravel and came across this package.. im trying to use it but keep getting different errors.
im getting:
`FatalErrorException in HomeController.php line 13:
Class 'App\Http\Controllers\JeroenG\Flickr\Flickr' not found`

Here is my HomeController.php

```
<?php

namespace App\Http\Controllers;
use Backpack\MenuCRUD\app\Models\MenuItem;
use Illuminate\Http\Request;
use App\Http\Requests;

class HomeController extends Controller
{
     public function __construct()
    {
        $flickr = new JeroenG\Flickr\Flickr(new JeroenG\Flickr\Api($key));
        $echoTest = $flickr->echoThis('helloworld');
    }
     public function index()
    {
        $this->data['menu_items'] = MenuItem::getTree();
        return view('welcome', $this->data);
    }
}
```

ive also tried adding `use JeroenG\Flickr;` but its the same.. is there any sample available?

**Comment by Jeroen-G** [comment]
Place a \ before JeroenG.
Or, if want to use the use statement, do `use JeroenG\Flickr\Flickr;` and `use JeroenG\Flickr\Api;`

**Comment by mpixelz** [comment]
Thanks for the reply..
still not working.. im now getting:

```
FatalErrorException in HomeController.php line 14:
Class 'App\Http\Controllers\JeroenG\Flickr\Flickr' not found
```

HomeController.php

```
<?php

namespace App\Http\Controllers;
use Backpack\MenuCRUD\app\Models\MenuItem;
use Illuminate\Http\Request;
use App\Http\Requests;
use JeroenG\Flickr\Flickr;
use JeroenG\Flickr\Api;

class HomeController extends Controller
{
    public function __construct()
    {
        $flickr = new JeroenG\Flickr\Flickr(new JeroenG\Flickr\Api($key));
        $echoTest = $flickr->echoThis('helloworld');
    }

     public function index()
    {
        $this->data['menu_items'] = MenuItem::getTree();
        return view('welcome', $this->data);
    }
}
```

**Comment by mpixelz** [comment]
that error is resolved but now its not passing the userId? ive tried many ways to pass the different variables such as userid, pages, per_page but keep getting error that user not found.
here is my HomeController.php

```
<?php

namespace App\Http\Controllers;
use Backpack\MenuCRUD\app\Models\MenuItem;
use Illuminate\Http\Request;
use App\Http\Requests;
use DebugBar\DebugBar;
use DebugBar\StandardDebugBar;
use JeroenG\Flickr\Flickr;
use JeroenG\Flickr\Api;

class HomeController extends Controller
{
    public function index()
    {
        $flickr = new \JeroenG\Flickr\Flickr(new \JeroenG\Flickr\Api(env('FLICKR_KEY', ''), 'php_serial'), (env('FLICKR_USERID', '')));
        $this->data['menu_items'] = MenuItem::getTree();
        //$test = $this->flickr->echoThis('helloworld');
        $photosets = $flickr->listSets();
        //$result = $flickr->request('flickr.photosets.getList', 'user_id=58119505@N02', 'page=1', 'per_page=10');
        $debugbar = new StandardDebugBar();
        $debugbar["messages"]->addMessage("hello world!");
        debug($flickr, $photosets);
        return view('welcome', $this->data);
    }
}
```

How can i pass the variable to get pictures for a particular userid?
my debug:

```
Response {#507 ▼
  #contents: array:3 [▼
    "stat" => "fail"
    "code" => 1
    "message" => "User not found"
  ]
}
```

**Comment by Jeroen-G** [comment]
You either do the use statement with 
`$flickr = new Flickr(...)`
Or without the use statement
`$flickr = new \JeroenG\Flickr\Flickr(...)`
Maybe you should read up a little bit on PHP namespacing.

**Comment by Jeroen-G** [comment]
Have a look at how I do it here: https://github.com/Jeroen-G/welpen/blob/master/app/Http/Controllers/AlbumController.php

**Comment by Jeroen-G** [comment]
@mpixelz Did you manage to get it to work?

**Comment by mpixelz** [comment]
@Jeroen-G yeah i got it to work.. if i add the use statement it doesnt work.. but using $flickr = new \JeroenG\Flickr\Flicker(...) worked for me.. thanks
