### ISSUE TITLE
(E_DEPRECATED) Non-static method JeroenG\Flickr\Flickr::echoThis() should not be called statically

### ISSUE THREAD

**Issue by dimitricappelle** [Jeroen-G/Flickr#4]
The laravel method $echoTest = Flickr::echoThis('helloworld'); in the documentation no longer works.
Error: (E_DEPRECATED) Non-static method JeroenG\Flickr\Flickr::echoThis() should not be called statically

**Comment by Jeroen-G** [comment]
It look likes you have not registered the Facade yet.
