### ISSUE TITLE
L5.5 compatible?

### ISSUE THREAD

**Issue by lauriek** [Jeroen-G/Flickr#5]
I'm not sure if I'm misusing this or if there is an incompatibility with Laravel 5.5?

I've instantiated your class with a correct api key. I then call ->photoInfo() with a valid flickr photo ID and my API secret (the photo is mine). 

What seems to happen is I should get a JeroenG\Flickr\Response object back, but in fact the constructor of that class is exploding because it cannot unserialise what comes back from $guzzleResponse->getBody()->getContents() (Which I think is effectively a chunk of XML in a string?)

The exact error is 

ErrorException (E_NOTICE)
unserialize(): Error at offset 0 of 2892 bytes

I'd really like to understand what's going wrong here as I'm keen to upgrade an old L4 site I have which uses the other flickr package, which is not compatible with L5...

**Comment by lauriek** [comment]
Follow up, I think the service provider is broken in L5.5, I've added it and the alias as per the instructions, and the env variables, but the class isn't available to me as just Flickr, I have to use the whole namespace path to use it. And because of that I wasn't aware of the 'php_serial' setting that I need to pass in with the key to the Api class.

Now I've added the php_serial setting, I have managed to get stuff working

**Comment by Jeroen-G** [comment]
Which PHP version are you on?
Can you show the code where you use the facade?
As far as I know the service provider shouldn't break with L5.5
The `php_serial` part refers back to  [the way Flickr formats its responses](https://www.flickr.com/services/api/response.php.html).

**Comment by lauriek** [comment]
I think the whole problem is that the facade is not working for me.

This is a fresh L5.5 install onto a vagrant box with PHP7.0,  bear in mind basically this is a test for me, first go with L5.5 and PHP7 so it's entirely possible I've done something dumb!

I'm pretty sure I followed the instructions from the readme.

I installed with composer within my laravel project. Seems to have correctly put code under vendor dir.

I added "JeroenG\Flickr\FlickrServiceProvider::class, " line to the providers array in app.php, and this line "'Flickr' => JeroenG\Flickr\FlickrLaravelFacade::class," to the aliases array. These look correct in terms of formatting compared to the other entries in both arrays.

I added FLICKR_KEY and FLICKR_SECRET defines to my .env file with correct values from my flickr API. (I also added a config file for this which gets those env variables, however I appreciate something in your code references the env vars direct)

However if I try even this

$echoTest = Flickr::echoThis('helloworld');

Then I get an error about calling a non static method statically. Which says to me the facade is not working.

A more realistic call

\JeroenG\Flickr\Flickr::photoInfo($photo->flickr_id, $secret);

Gives exactly the same error about static methods.

If I manually instantiate your class without the format parameter which is supposed to be optional, then I cannot make any requests as the thing mentioned in my first comment occurs, where the return is unserialisable.

I can however manually instantiate the class with the php_serial format and then it works.

My code looks weird because this is in my own helper class which is also called Flickr (unhelpful I know!) so I use your Flickr class as JeroenG! (this is all very temporary code right now while I'm getting my head around making this work!!) The following works fine. (part of this code is in the constructor and part in a method but glommed together here for simplicity)

$key = config('flickr.key');
$this->flickr = new JeroenG(new Api($key, 'php_serial')) ;

$parameters = ['user_id' => $this->flickr_user_id]; // that's my user id from another config entry
$collections = $this->flickr->request('flickr.collections.getTree', $parameters);
return $collections->collections;

**Comment by lauriek** [comment]
There's probably something I'm missing but shouldn't the default format in your Api constructor be php_serial? Given that the request method attempts to return a Response object, which attempts to unserialise the guzzle response, which explodes if not in php_serial format?

**Comment by Jeroen-G** [comment]
It probably should be, yes. Maybe you would like to contribute? :)

Does `$echo = \Flickr::echoThis('helloworld');` also not work? The facade lives in the global namespace IIRC.
Could you write a test that I could run to see if I can replicate the issue?

**Comment by Jeroen-G** [comment]
I tested this on L5.5, PHP7
```php
Route::get('flickr', function () {
    var_dump(Flickr::echoThis('hello world'));
});
```
It returned the right Flickr response object.
