### ISSUE TITLE
A question about accessing photos

### ISSUE THREAD

**Issue by sunscreem** [Jeroen-G/Flickr#7]
Hey, 

Thanks again for sharing this package. Can I get a quick sanity check on my own code?

This is how I'm fetching (and popping into a collection) a users recent photos:

```
 $flickrRequest = Flickr::request(
                'flickr.photos.getRecent',
                ['user_id' => config('site.flickrUserId')]
            );

  return collect($flickrRequest->photos['photo']);
```

Is that how you intended the package to be used? 

If so I'll maybe add a PR for an example to the readme?

**Comment by Jeroen-G** [comment]
I think I would put Flickr in the services config or .env
You're also giving me the idea to return results as collections automatically!
Is this how you like to write it? Because maybe I can work towards more readable code (for example, not having to pass user id for every request).

**Comment by sunscreem** [comment]
Hey - I had a thought last night about rewriting my code a little, so bear with me. I'll move things around a bit today (or tomorrow) and come back to you with my final implementation.

I read up about [using resources](https://medium.com/@jeffochoa/consuming-third-pary-apis-with-laravel-resources-c13a0c7dc945) last night and its got me thinking about a refactor.

The project I'm working on (just a basic "pull the photos in from flickr and display them") needs to be added to three of my client sites so I was considering turning my code into a proper package on git, of which your code will, of course, be a dependency. It's not something I've done before but might be worth a shot!
