### ISSUE TITLE
Caching the application config breaks the package

### ISSUE THREAD

**Issue by jorisnoo** [Jeroen-G/Flickr#8]
Thanks a lot for your work!

I'm currently running into an issue when calling `php artisan config:cache`: This makes calls to `env()` return `null`. However, in the `FlickrServiceProvider`, the API key is accessed through `env('FLICKR_KEY')`.

As as solution, the package could eg. either publish its own config file to the `config` folder, or possibly require setting the FLICKR_KEY in the `config/services.php` file?

For example, adding
```
'flickr' => [
        'key' => env('FLICKR_KEY'),
],
```
to `config/services.php` and then accessing the key with `config('services.flickr.key')` in the `FlickrServiceProvider`.

Let me know if you'd like me to create a pull request. :v:

**Comment by Jeroen-G** [comment]
That is indeed the best practice. Please do create a PR! Fetching it from the services config should be fine.

**Comment by jorisnoo** [comment]
I hope this will do the trick #9

**Comment by Jeroen-G** [comment]
Available in v1.2 ✨
